# Generated by Django 4.2.7 on 2023-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.CharField(max_length=255, unique=True)),
                ('produto', models.CharField(max_length=255, unique=True)),
                ('quantidade', models.CharField(max_length=255, unique=True)),
                ('preco_unitario', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
